apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: scratchpay
type: Opaque
data:
  DB_NAME: dXNlcnNkYg==
  DB_USER: dGVjaC11c2Vy
  DB_PASS: dGVjaC1wdw==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-certificate
  namespace: scratchpay
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lVYjk0ekZSRTVV
    a3lOKzZlYkNHeWdjNC8xSkQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pi
    RzlqWVd4b2IzTjBNQjRYRFRJeU1EY3dPVEl4TlRjek9Wb1hEVE15TURjdwpOakl4TlRjek9Wb3dG
    REVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NB
    UThBTUlJQkNnS0NBUUVBOTRHT1NBUjFGWWFWVW5tdUlWalVBWS9Da1RnUHFaWUVkWncwUjRJWTNo
    ZHcKYUlTL1FDR0VnWkV4MHRDMFAxWnBvOURMYi9QeEw2SkpYSUxmZFdOTlFXTnlYYU1JbGhEZ1k3
    R2tKMkdBbXhhNwpXYzZSQmdSbGIzKzV3OXF3RVc2WlkwdDVuS0pPSmZnV2FVTVRKbnQvaUY2bWdt
    V2dzV09NaW8yYm1ySldYb3I2CjVzR2xLMk56VjIyK2JTdGpDdWJwdjliVm0zRXlDRGYxTG9ZS3pJ
    bGljRE4yMXBUMU1zNXZjbDMwNDFGTHZ3eW0KNU9vSVJ4Z0VmUmRLYW5KR2lCQWZhVzR2Z2VFMkdz
    bVJZQjNDaGF4SWphTG9NcUxESUpHUUtXSnV0WDNQd3JDYgpvRlVxM1lhY2JJTTJOZjY5azF1TVBW
    STlvL3ZobENOcC9jUS9LeEFMK1FJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVIZERCdHdKREFU
    L3VFZzdiY0JNTjJpWE1zdkl3SHdZRFZSMGpCQmd3Rm9BVUhkREJ0d0pEQVQvdUVnN2IKY0JNTjJp
    WE1zdkl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBM290
    Qwo2Y2UzWHYvaW9FQTdzSXZacWgxOFI0M1R3UzdEbllNa0U2UUttU0F3azYrWnh2d2d3VnhUQXBv
    OE1SenRCaXhECnpoT1cydERBSlpxMlUxNmdTWlovRzl4OGE1RC9ZN0tsWCtWbWp5RUZsS1BZYjJB
    ajZabGl4VHJDcWVJR3BsSHEKazZlQklRQmh0emNjeHdsUFhZNUVEamVxQ0ZqUE92dmRPd21NWUlT
    c2hSRGFhWUQ0SVRnaGZCb3MrblhZQm5uUApXZ1gyblVPdlY4ZUJqNGlDajRLcHZPRi9BbFVOWmQr
    N1drOFkyeGMyMFBSZjg5ZWFGZTVTS3ZVbkxzdlczYlJOCkpwckRuNk14SkE2UXJ2TkIzNUkzcnFZ
    dXZXUU51Y3RCaktoYWVlWEJ6T2RKYmFoUDlNMEJXc0M5d0c3SGFJRUMKd1BZVnFYRUozRkZnTkha
    MHh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRRDNnWTVJQkhVVmhwVlMKZWE0aFdOUUJqOEtST0ErcGxnUjFu
    RFJIZ2hqZUYzQm9oTDlBSVlTQmtUSFMwTFEvVm1tajBNdHY4L0V2b2tsYwpndDkxWTAxQlkzSmRv
    d2lXRU9CanNhUW5ZWUNiRnJ0WnpwRUdCR1Z2ZjduRDJyQVJicGxqUzNtY29rNGwrQlpwClF4TW1l
    MytJWHFhQ1phQ3hZNHlLalp1YXNsWmVpdnJtd2FVclkzTlhiYjV0SzJNSzV1bS8xdFdiY1RJSU4v
    VXUKaGdyTWlXSndNM2JXbFBVeXptOXlYZlRqVVV1L0RLYms2Z2hIR0FSOUYwcHFja2FJRUI5cGJp
    K0I0VFlheVpGZwpIY0tGckVpTm91Z3lvc01na1pBcFltNjFmYy9Dc0p1Z1ZTcmRocHhzZ3pZMS9y
    MlRXNHc5VWoyaisrR1VJMm45CnhEOHJFQXY1QWdNQkFBRUNnZ0VBUDlzOHBzY0RvRUNmVU82VTV3
    U2dlaUNwamNiOWYzNzFlcFNKQm5RQnozY1QKcU51cTdqUlhtQWdxWng0eWl1N1VCWkJPbEgxSEdr
    ZVFEdDZ6SVhtenltMkthYTh3L1dxd1FmaG9oa0tKS0RwRwpyd1owOHl6Nk1MaXU2R0dKTUk0czQr
    bnFuK2RlS3p5bEo1WkhJQlFYMU1xNndnVFBYMFQwVXlEeTV3Z2c4WFgvCkhQSm11VGEzV3V0czVK
    M2hWZXRDVzI1dTBOZXlJZVY3ZWdvY0QvVnJXd3RDM001UmdyR0ZSaFJFNGtsaVBGNzMKeVJmRnN0
    ZUU2RCtiOSs1Mjc0SGJ3anFrMWlpTjNjTjkweU1kQ05QSFlyZGtrL2RHMlYyQ2EyMnMxeDdxZ1RP
    MQp4OUd0VExBRW5EL1B1WG44QStJVjliNGdZampQb054V0ppQmZVbXg2S3dLQmdRRCsyZWxPMVZy
    OVkydlRBVmdSCm5nYThzck1ObFQxV0tkYk1DS0d4Q3pmWHFoNSs3OTNZOXdDeHAvMUlMdjhiL2lD
    SDRxNm0xeVUxVi9jUzhpU2UKckZ5ZUJpczdHbG9TeFFSS1FHY3JhOXN1VWJua3hLSFlxdit4dGEv
    MDJ0OHJlU2kvTEhqUTFnZWliampRUloyUwpHdkFSeDJPYnJ1Qk1ocnpqNGFrS1JiQlg3d0tCZ1FE
    NG55c2RSVDVNZFlWa3M3a0JRcWZON2U1aW9naTVkKzVNCitEd3RreDQ5NysyUFBpZkppMnNsN0pK
    R1hOSTBndWwvM2pKM1ZCWkZoZWo1VlY0NmtYcWFwZVZDQkVNVzZraTcKZGNsdjlOckVMeUtZV2hx
    VTNJRGNzR1NzWlR1aktGRXlnbnEzc21jU3NzRzhDNCtUTXQwYjJmaHhFR2tNeDROcApWQ0FIazVp
    eWx3S0JnUUNpZHVKL3lnMm1hU0lNc3RlazYzdmFBWVdaekNEODg5RWw0djdJOGFEWTBHOStkb1dU
    CjBlclVWb1psNU9mbXZYdVpoTTNZT0dGVS8wM1greHVUTjhnWFNWRjM3UldzejRJcm42RGxrbTE0
    dXNycDV0eFMKVnJpSVhvM2NaMGRMM0lJNFZTNXoyMjJrZytXZUNETXFPQmdCRFg0WGVrVXRJOXY0
    M2h1NEc3TU9hd0tCZ1FETwpkNWhkYVhpUUZIU2ZxV1QxTi82VTFJZkluMWx4ZExpUWNRSEFzMUZG
    REhBVEtnSHVyUHBoZHpJT2Z0ME9RTDFhCnRCTGk2QkRLMGFjbEVKRDlRSDA1MnBVbUd0WUFQTFlE
    LzVBMmluZjJ2bElUaFpoWGtUcnVpd28vNUozL0krY3kKZEFzbmJGK090cWFPM0dieVRpWXpEL1B6
    S1Rha0p6ZnBpN1JCdG4venB3S0JnUURSZitMZWRDd3ZaWS8wdEhpTwpzOENNMkcwLzlqbHM3Wkcr
    L2xReVg4Z2g2RDJIS3hWL1dIZm9sdXc2clg0VkZISW1yc2xwTVNOVnhzTkhMeHNJCko4SFYrT29x
    dWFBUm5yNEcyOHB6UjJYdXp3VjRzelJpdkNER2phaFZTU1BRdUlrM2QyTjh3ZlVsaDVPWUtwTWsK
    SThSOERmNFJCZWtiVytib29LR0FLdURjeXc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
