apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: scratchpay
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdC1wdw==
  MYSQL_DATABASE: dXNlcnNkYg==
  MYSQL_USER: dGVjaC11c2Vy
  MYSQL_PASSWORD: dGVjaC1wdw==
